/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify that the API is running.
         *     Returns a simple JSON response indicating the status of the API.
         */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Waitlist Items
         * @description Endpoint to retrieve waitlist items.
         *     Returns a list of waitlist items in JSON format.
         */
        get: operations["get_waitlist_items_api_v1_waitlist_items_get"];
        put?: never;
        /**
         * Create Waitlist Item
         * @description Endpoint to create a new waitlist item.
         *     Accepts a WaitListItemInput object in the request body and returns the
         *     created waitlist item, including its assigned id and priority.
         */
        post: operations["create_waitlist_item_api_v1_waitlist_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Waitlist Item
         * @description Endpoint to delete a waitlist item by its ID.
         *     Returns a confirmation message upon successful deletion.
         */
        delete: operations["delete_waitlist_item_api_v1_waitlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calendar Items
         * @description Endpoint to retrieve calendar items.
         *     Returns a list of calendar items in JSON format.
         */
        get: operations["get_calendar_items_api_v1_calendar_items_get"];
        put?: never;
        /**
         * Create Calendar Item
         * @description Endpoint to create a new calendar item.
         *     Accepts a CalendarItemInput object in the request body and returns the
         *     created calendar item, including its assigned id.
         */
        post: operations["create_calendar_item_api_v1_calendar_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Calendar Item
         * @description Endpoint to update an existing calendar item.
         *     Replaces the calendar item identified by item_id with the supplied data
         *     and returns the updated item.
         */
        put: operations["update_calendar_item_api_v1_calendar_items__item_id__put"];
        post?: never;
        /**
         * Delete Calendar Item
         * @description Endpoint to delete a calendar item by its ID.
         *     Returns a confirmation message upon successful deletion.
         */
        delete: operations["delete_calendar_item_api_v1_calendar_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patients
         * @description Endpoint to retrieve all known patients (id and name), used by the chat
         *     client to populate its patient selector.
         */
        get: operations["get_patients_api_v1_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description Endpoint to retrieve messages for a specific patient.
         *     Returns a list of messages in JSON format.
         */
        get: operations["get_messages_api_v1_messages__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recent-messages/{patient_id}/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recent Messages
         * @description Endpoint to retrieve recent messages for a specific patient starting from a specific message ID.
         *     Pass -1 to receive the full history. Returns a list of messages in JSON format.
         */
        get: operations["get_recent_messages_api_v1_recent_messages__patient_id___message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Message
         * @description Endpoint to create a new message.
         *     Accepts a MessageInput object in the request body and returns the created
         *     message, including its assigned id and timestamp.
         */
        post: operations["create_message_api_v1_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Jobs
         * @description Endpoint to retrieve agent jobs.
         *     Returns a list of agent jobs in JSON format.
         */
        get: operations["get_agent_jobs_api_v1_agent_jobs_get"];
        put?: never;
        /**
         * Create Agent Job
         * @description Endpoint to create a new agent job.
         *     Accepts an AgentJob object in the request body and returns a confirmation message.
         */
        post: operations["create_agent_job_api_v1_agent_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Agent Job
         * @description Endpoint to delete an agent job by its ID.
         *     Returns a confirmation message upon successful deletion.
         */
        delete: operations["delete_agent_job_api_v1_agent_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentJob
         * @description Pydantic model representing an agent job.
         */
        AgentJob: {
            /** Id */
            id: number;
            /** Job Type */
            job_type: string;
            status: components["schemas"]["AgentJobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentJobInput
         * @description Pydantic model representing input data for an agent job.
         */
        AgentJobInput: {
            /** Job Type */
            job_type: string;
        };
        /**
         * AgentJobStatus
         * @description Enumeration of possible agent job statuses.
         * @enum {string}
         */
        AgentJobStatus: "created" | "in_progress" | "completed" | "failed";
        /**
         * AppointmentStatus
         * @description Enumeration of possible appointment statuses.
         * @enum {string}
         */
        AppointmentStatus: "scheduled" | "canceled";
        /**
         * CalendarItem
         * @description Pydantic model representing a calendar item.
         */
        CalendarItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Patient Id */
            patient_id: number;
            /** Patient Name */
            patient_name: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            status: components["schemas"]["AppointmentStatus"];
        };
        /**
         * CalendarItemInput
         * @description Pydantic model representing input data for a calendar item.
         */
        CalendarItemInput: {
            /** Title */
            title: string;
            /** Patient Id */
            patient_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** @default scheduled */
            status: components["schemas"]["AppointmentStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Message
         * @description Pydantic model representing a message.
         */
        Message: {
            /** Id */
            id: number;
            /** Patient Id */
            patient_id: number;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * MessageInput
         * @description Pydantic model representing input data for a message.
         */
        MessageInput: {
            /** Patient Id */
            patient_id: number;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
        };
        /**
         * MessageRole
         * @description Enumeration of possible message roles.
         * @enum {string}
         */
        MessageRole: "system" | "user" | "assistant";
        /**
         * Patient
         * @description Pydantic model representing a patient known to the system.
         */
        Patient: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WaitListItem
         * @description Pydantic model representing a waitlist item.
         */
        WaitListItem: {
            /** Id */
            id: number;
            /** Patient Name */
            patient_name: string;
            /** Patient Id */
            patient_id: number;
            /** Priority */
            priority: number;
        };
        /**
         * WaitListItemInput
         * @description Pydantic model representing input data for a waitlist item.
         */
        WaitListItemInput: {
            /** Patient Name */
            patient_name: string;
            /** Patient Id */
            patient_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_waitlist_items_api_v1_waitlist_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitListItem"][];
                };
            };
        };
    };
    create_waitlist_item_api_v1_waitlist_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitListItemInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_waitlist_item_api_v1_waitlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_items_api_v1_calendar_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"][];
                };
            };
        };
    };
    create_calendar_item_api_v1_calendar_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarItemInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_calendar_item_api_v1_calendar_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarItemInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_calendar_item_api_v1_calendar_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patients_api_v1_patients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"][];
                };
            };
        };
    };
    get_messages_api_v1_messages__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recent_messages_api_v1_recent_messages__patient_id___message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_jobs_api_v1_agent_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentJob"][];
                };
            };
        };
    };
    create_agent_job_api_v1_agent_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentJobInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_job_api_v1_agent_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
